repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: trailing-whitespace
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/futuretech6/pre-commit-rust-nightly
    rev: v1.1
    hooks:
      - id: fmt
        args: ['--', '--unstable-features']
